/***
 ***  generated by CSeq [ 0000 / 0000 ] 2024-05-07 22:10:21
 ***
 ***                      822D 2021.02.15 core/merger
 ***                      1EE3 2021.10.18 core/module
 ***                      4EA7 2021.02.04 core/parser
 ***                      0328 2020.12.21 core/utils
 ***
 ***  params:
 ***    --backend CPAchecker -i examples/deadlock_loop.c --deadlock  --unwind-while 30
 ***
 ***  modules:
 ***    7D72 workarounds (sv-comp)
 ***    FE0F functiontracker ()
 ***    E288 preinstrumenter (sv-comp error-label)
 ***    E30D constants (deep-propagation)
 ***    6C2E spinlock ()
 ***    4FEF switchtransformer ()
 ***    43C1 dowhileconverter ()
 ***    D564 conditionextractor ()
 ***    5C53 varnames ()
 ***    82A6 preinliner ()
 ***    52F2 inliner (atomic-parameters simplify-args)
 ***    CDF9 unroller (unwind unwind-while unwind-for unwind-for-max softunwindbound varnamesmap varscopesmap extra-tracking unwind-check)
 ***    0000 duplicator (threads)
 ***    0000 condwaitconverter ()
 ***    0000 racedetector (data-race-check)
 ***    0000 lazyseq (rounds contexts threads schedule deadlock nondet-condvar-wakeups varnamesmap)
 ***    252C instrumenter (backend bitwidth header)
 ***    0A81 mapper (backend contexts unwind cores reuse-dimacs)
 ***    75B6 feeder (backend time llvm unwind contexts unwind 32 show-backend-output extrargs from to extra)
 ***    79CC cex (backend cex threadnamesmap threadindexes threadindextoname varnamesmap coordstofunctions sv-comp witness entry threadsizes threadendlines loopheads unwind-check)
 ***
 ***/
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
extern void __VERIFIER_assume(int);
extern int __VERIFIER_nondet_int(void);
extern unsigned int __VERIFIER_nondet_uint(void);
extern _Bool __VERIFIER_nondet_bool(void);
extern char __VERIFIER_nondet_char(void);
extern unsigned char __VERIFIER_nondet_uchar(void);
//#include <stdio.h>
//#include <stdlib.h>
#define THREADS 2
#define ROUNDS 1
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A)  |  (A >= __cs_pc_cs[T])) goto B;
#ifndef NULL
#define NULL 0
#endif
                         
                         _Bool __cs_loop_check = (1);
                         
                         unsigned int __cs_active_thread[THREADS + 1] = {1};
                         
                         unsigned int __cs_pc[THREADS + 1];
                         
                         unsigned int __cs_pc_cs[THREADS + 1];
                         
                         unsigned int __cs_thread_index;
                         
                         unsigned int __cs_last_thread;
                         
                         unsigned int __cs_thread_lines[] = {5, 5, 5};
                         
                         void __cs_init_scalar(void *__cs_var, unsigned int __cs_size)
                         {
                                   
                                   if (__cs_size == (sizeof(int)))
                                             
                                   * ((int *) __cs_var) = (__VERIFIER_nondet_int());
                                   else
                         
                                             {
                                             
                                             __cs_var = (malloc(__cs_size));
                                   }
                         }
                         
                         
                         void __CSEQ_message(char *__cs_message)
                         {
                                   ;
                         }
                         
                         
                         typedef int cspthread_t;
                         
                         void *__cs_threadargs[THREADS + 1];
                         
                         typedef int cspthread_key_t;
                         
                         cspthread_key_t __cs_keys[1][THREADS + 2];
                         
                         void (*__cs_key_destructor[1])(void *);
                         
                         int pthread_create_2(cspthread_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_func)(void *), void *__cs_arg, int __cs_threadID)
                         {
                                   
                                   if (__cs_threadID > THREADS)
                                             return (0);
                                   
                                   * __cs_new_thread_id = (__cs_threadID);
                                   
                                   __cs_active_thread[__cs_threadID] = (1);
                                   
                                   __cs_threadargs[__cs_threadID] = (__cs_arg);
                                   
                                   __CSEQ_message("thread spawned");
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_join(cspthread_t __cs_id, void **__cs_value_ptr)
                         {
                                   
                                   __VERIFIER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                   
                                   return (0);
                         }
                         
                         
                         void pthread_exit(void *__cs_value_ptr)
                         {
                                   
                                   if ((__cs_key_destructor[0] != 0) && (__cs_keys[0][__cs_thread_index + 1] != 0))
                                   {
                                             
                                             __cs_key_destructor[0]((void *) __cs_keys[0][__cs_thread_index + 1]);
                                   }
                         }
                         
                         
                         int pthread_self(void)
                         {
                                   return (__cs_thread_index + 1);
                         }
                         
                         
                         typedef int cspthread_mutex_t;
                         
                         typedef int cspthread_mutexattr_t;
                         
                         int pthread_mutex_init(cspthread_mutex_t *__cs_m, cspthread_mutexattr_t *__cs_val)
                         {
                                   
                                   * __cs_m = (- 1);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_mutex_destroy(cspthread_mutex_t *__cs_mutex_to_destroy)
                         {
                                   
                                   * __cs_mutex_to_destroy = (- 2);
                                   
                                   __CSEQ_message("lock destroyed");
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_mutex_lock(cspthread_mutex_t *__cs_mutex_to_lock)
                         {
                                   
                                   __VERIFIER_assume((* __cs_mutex_to_lock) == (- 1));
                                   
                                   * __cs_mutex_to_lock = (__cs_thread_index + 1);
                                   
                                   __CSEQ_message("lock acquired");
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_mutex_unlock(cspthread_mutex_t *__cs_mutex_to_unlock)
                         {
                                   
                                   __VERIFIER_assume((* __cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                   
                                   * __cs_mutex_to_unlock = (- 1);
                                   
                                   __CSEQ_message("lock released");
                                   
                                   return (0);
                         }
                         
                         
                         typedef int cspthread_cond_t;
                         
                         typedef int cspthread_condattr_t;
                         
                         int pthread_cond_init(cspthread_cond_t *__cs_cond_to_init, cspthread_condattr_t *__cs_attr)
                         {
                                   
                                   * __cs_cond_to_init = (- 1);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_cond_destroy(cspthread_cond_t *__cs_cond_to_destroy)
                         {
                                   
                                   * __cs_cond_to_destroy = (- 2);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_cond_wait_1(cspthread_cond_t *__cs_cond_to_wait_for, cspthread_mutex_t *__cs_m)
                         {
                                   
                                   pthread_mutex_unlock(__cs_m);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_cond_wait_2(cspthread_cond_t *__cs_cond_to_wait_for, cspthread_mutex_t *__cs_m)
                         {
                                   
                                   __VERIFIER_assume((* __cs_cond_to_wait_for) == 1);
                                   
                                   pthread_mutex_lock(__cs_m);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_cond_signal(cspthread_cond_t *__cs_cond_to_signal)
                         {
                                   
                                   * __cs_cond_to_signal = (1);
                                   
                                   __CSEQ_message("conditional variable signal");
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_cond_broadcast(cspthread_cond_t *__cs_cond_to_broadcast)
                         {
                                   
                                   * __cs_cond_to_broadcast = (1);
                                   
                                   __CSEQ_message("conditional variable broadcast");
                                   
                                   return (0);
                         }
                         
                         
                         typedef struct cspthread_barrier_t
                         {
                                   
                                   unsigned int init;
                                   
                                   unsigned int current;
                         } cspthread_barrier_t;
                         
                         typedef int cspthread_barrierattr_t;
                         
                         int pthread_barrier_init(cspthread_barrier_t *__cs_barrier_to_init, cspthread_barrierattr_t *__cs_attr, unsigned int count)
                         {
                                   
                                   __cs_barrier_to_init->current = (count);
                                   
                                   __cs_barrier_to_init->init = (count);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_barrier_destroy(cspthread_barrier_t *__cs_barrier_to_destroy)
                         {
                                   
                                   __cs_barrier_to_destroy->init = (- 1);
                                   
                                   __cs_barrier_to_destroy->current = (- 1);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_barrier_wait_1(cspthread_barrier_t *__cs_barrier_to_wait)
                         {
                                   
                                   __cs_barrier_to_wait->current--;
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_barrier_wait_2(cspthread_barrier_t *__cs_barrier_to_wait)
                         {
                                   
                                   __VERIFIER_assume(__cs_barrier_to_wait->current == 0);
                                   
                                   __cs_barrier_to_wait->current = (__cs_barrier_to_wait->init);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_key_create(cspthread_key_t *key, void (*destructor)(void *))
                         {
                                   
                                   static int currentkey = (0);
                                   
                                   __cs_key_destructor[0] = (destructor);
                                   
                                   * key = (currentkey++);
                                   
                                   return (0);
                         }
                         
                         
                         int pthread_setspecific(cspthread_key_t key, void *value)
                         {
                                   
                                   __cs_keys[key][__cs_thread_index + 1] = ((cspthread_key_t) value);
                                   
                                   return (0);
                         }
                         
                         
                         void *pthread_getspecific(cspthread_key_t key)
                         {
                                   
                                   return ((void *) __cs_keys[key][__cs_thread_index + 1]);
                         }
                         
                         
                         void __CSEQ_noop(void)
                         {
                         }
                         
                         
                         
                         cspthread_mutex_t l1;
                         
                         cspthread_mutex_t l2;
                         
                         int counter = (0);
                         
                         int task1_0()
                         
                         {
                                   
IF(1,0,ttask1_0_1)
                                   
                                   pthread_mutex_lock(& l1);
                                   
ttask1_0_1: IF(1,1,ttask1_0_2)
                                   
                                   pthread_mutex_lock(& l2);
                                   
ttask1_0_2: IF(1,2,ttask1_0_3)
                                   
                                   counter++;
                                   
ttask1_0_3: IF(1,3,ttask1_0_4)
                                   
                                   pthread_mutex_unlock(& l2);
                                   
ttask1_0_4: IF(1,4,ttask1_0_5)
                                   
                                   pthread_mutex_unlock(& l1);
                                   
                                   __exit_task1:
                                   __VERIFIER_assume(__cs_pc_cs[1] >= 5);
                         
                                   
                                   ;
                                   ;
                                   
ttask1_0_5: 
                                   
                                   pthread_exit(0);
                         }
                         
                         
                         int task2_0()
                         
                         {
                                   
IF(2,0,ttask2_0_1)
                                   
                                   pthread_mutex_lock(& l2);
                                   
ttask2_0_1: IF(2,1,ttask2_0_2)
                                   
                                   pthread_mutex_lock(& l1);
                                   
ttask2_0_2: IF(2,2,ttask2_0_3)
                                   
                                   counter++;
                                   
ttask2_0_3: IF(2,3,ttask2_0_4)
                                   
                                   pthread_mutex_unlock(& l1);
                                   
ttask2_0_4: IF(2,4,ttask2_0_5)
                                   
                                   pthread_mutex_unlock(& l2);
                                   
                                   __exit_task2:
                                   __VERIFIER_assume(__cs_pc_cs[2] >= 5);
                         
                                   
                                   ;
                                   ;
                                   
ttask2_0_5: 
                                   
                                   pthread_exit(0);
                         }
                         
                         
                         int main_thread(void)
                         
                         {
                                   
IF(0,0,tmain_1)
                                   
                                   static cspthread_t __cs_local_main_id1;
                                   __cs_local_main_id1 = (0);
                                   
                                   static cspthread_t __cs_local_main_id2;
                                   __cs_local_main_id2 = (0);
                                   
                                   pthread_mutex_init(& l1, 0);
                                   
                                   pthread_mutex_init(& l2, 0);
                                   
                                   pthread_create_2(& __cs_local_main_id1, 0, task1_0, 0, 1);
                                   
tmain_1: IF(0,1,tmain_2)
                                   
                                   pthread_create_2(& __cs_local_main_id2, 0, task2_0, 0, 2);
                                   
tmain_2: IF(0,2,tmain_3)
                                   
                                   pthread_join(__cs_local_main_id1, 0);
                                   
tmain_3: IF(0,3,tmain_4)
                                   
                                   pthread_join(__cs_local_main_id2, 0);
                                   
                                   static _Bool __cs_local_main___cs_tmp_if_cond_0;
                                   
tmain_4: IF(0,4,tmain_5)
                                   
                                   __cs_local_main___cs_tmp_if_cond_0 = (counter < 2);
                                   
                                   if (__cs_local_main___cs_tmp_if_cond_0)
                         
                                             {
                                             
                                             __VERIFIER_error();
                                   }
                                   
                                   ;
                                   
                                   goto __exit_main;
                                   ;
                                   
                                   __exit_main:
                                   __VERIFIER_assume(__cs_pc_cs[0] >= 5);
                         
                                   
                                   ;
                                   ;
                                   
tmain_5: 
                                   
                                   pthread_exit(0);
                         }
                         
                         
                         int main(void)
                         {
                                   
/* round  0 */
                                   
/* main */
                                   
                                   __cs_thread_index = (0);
                                   
                                   unsigned int __cs_tmp_t0_r0;
                                   
                                   __cs_pc_cs[0] = (__cs_tmp_t0_r0);
                                   
                                   __VERIFIER_assume(__cs_pc_cs[0] > 0);
                                   
                                   __VERIFIER_assume(__cs_pc_cs[0] <= 5);
                                   
                                   main_thread();
                                   
                                   __cs_pc[0] = (__cs_pc_cs[0]);
                                   
/* task1_0 */
                                   
                                   unsigned int __cs_tmp_t1_r0;
                                   
                                   if (__cs_active_thread[1])
                                   {
                                             
                                             __cs_thread_index = (1);
                                             
                                             __cs_pc_cs[1] = (__cs_tmp_t1_r0);
                                             
                                             __VERIFIER_assume(__cs_pc_cs[1] <= 5);
                                             
                                             task1_0(__cs_threadargs[1]);
                                             
                                             __cs_pc[1] = (__cs_pc_cs[1]);
                                   }
                                   
/* task2_0 */
                                   
                                   unsigned int __cs_tmp_t2_r0;
                                   
                                   if (__cs_active_thread[2])
                                   {
                                             
                                             __cs_thread_index = (2);
                                             
                                             __cs_pc_cs[2] = (__cs_tmp_t2_r0);
                                             
                                             __VERIFIER_assume(__cs_pc_cs[2] <= 5);
                                             
                                             task2_0(__cs_threadargs[2]);
                                             
                                             __cs_pc[2] = (__cs_pc_cs[2]);
                                   }
                                   
                                   unsigned int __cs_tmp_t0_r1;
                                   
                                   if (__cs_active_thread[0])
                                   {
                                             
                                             __cs_thread_index = (0);
                                             
                                             __cs_pc_cs[0] = (__cs_tmp_t0_r1);
                                             
                                             __VERIFIER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                             
                                             __VERIFIER_assume(__cs_pc_cs[0] <= 5);
                                             
                                             main_thread();
                                   }
                                   
                                   return (0);
                         }
                         
                         
